spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5432/sharetext_auth}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:maoirt}

server:
  port: 8081

security:
  jwt:
    token:
      secret-key: secret-value

#
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka