spring:
  application:
    name: TEXT-SERVICE

  datasource:
    url: ${ShareText_DB_URL:jdbc:postgresql://localhost:5432/text}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:142536}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka